# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
food_list = [
  ['Alcoholic beer, regular', 153],
  ['Alcoholic wine, table red', 88],
  ['Alfalfa seeds, sprouted, raw', 8],
  ['Apple juice, canned unsweetened', 117],
  ['Apples, dried,', 78],
  ['Apples, raw, with skin', 72],
  ['Apples, raw, without skin', 53],
  ['Apricots, dried, uncooked', 84],
  ['Apricots, raw', 17],
  ['Artichokes, cooked', 64],
  ['Artichokes, raw', 110],
  ['Asparagus, cooked', 13],
  ['Avocados, raw', 47],
  ['Bamboo shoots, canned', 25],
  ['Bananas, raw', 105],
  ['Barley, pearled, cooked', 193],
  ['Barley, pearled, raw', 704],
  ['Beans, black cooked', 227],
  ['Beans, great northern cooked', 209],
  ['Beans, kidney red, cooked', 225],
  ['Beans, navy cooked', 255],
  ['Beans, pinto cooked', 245],
  ['Beans, snap green, cooked', 44],
  ['Beef, ground, 85% lean, broiled', 213],
  ['Beef, sirloin, trimmed to 1/8″ fat, broiled', 207],
  ['Beet greens, boiled', 39],
  ['Beets, boiled', 22],
  ['Blackberries, raw', 62],
  ['Blueberries, raw', 83],
  ['Bread, cracked-wheat', 65],
  ['Bread, Multi-Grain', 69],
  ['Bread, oatmeal', 73],
  ['Bread, pita, white', 77],
  ['Bread, pumpernickel', 80],
  ['Bread, rye', 83],
  ['Bread, wheat', 67],
  ['Broccoli, boiled,', 55],
  ['Broccoli, raw', 30],
  ['Brussels sprouts, boiled', 56],
  ['Buckwheat flour, whole-groat', 402],
  ['Buckwheat groats, roasted', 155],
  ['Bulgur, cooked', 151],
  ['Bulgur, dry', 479],
  ['Butter', 102],
  ['Cabbage, boiled', 35],
  ['Cabbage, Chinese, boiled', 17],
  ['Cabbage, raw', 18],
  ['Cake, angelfood, commercially prepared', 72],
  ['Candies, milk chocolate coated raisins', 39],
  ['Candies, milk chocolate, with almonds', 216],
  ['Carbonated beverage, cola, contains caffeine', 137],
  ['Carob flour', 18],
  ['Carrot juice, canned', 94],
  ['Carrots, baby, raw', 4],
  ['Carrots, boiled', 55],
  ['Carrots, raw', 45],
  ['Catsup', 15],
  ['Cauliflower, boiled', 29],
  ['Cauliflower, raw', 25],
  ['Celery, raw', 6],
  ['Cereal Oats, cooked with water', 166],
  ['Cheese, blue', 100],
  ['Cheese, camembert', 114],
  ['Cheese, cheddar', 114],
  ['Cheese, cottage', 216],
  ['Cheese, cream', 51],
  ['Cheese, feta', 75],
  ['Cheese, mozzarella, part skim', 86],
  ['Cheese, parmesan, grated', 22],
  ['Cheese, provolone', 100],
  ['Cheese, ricotta, part skim milk', 339],
  ['Cheese, swiss', 108],
  ['Cherries, sweet', 43],
  ['Chicken breast meat only, roasted', 142],
  ['Chicken drumstick meat only, roasted', 76],
  ['Chicken, thigh meat only, roasted', 109],
  ['Chickpeas, boiled', 269],
  ['Collards, boiled', 49],
  ['Cookies, fig bars', 56],
  ['Cookies, graham crackers', 59],
  ['Corn, sweet, yellow, boiled', 83],
  ['Cornmeal, whole-grain, yellow', 442],
  ['Couscous, cooked', 176],
  ['Cowpeas boiled', 160],
  ['Crab, Alaska king, cooked', 82],
  ['Crab, blue, cooked', 87],
  ['Crackers, melba toast, plain', 78],
  ['Crackers, rye, wafers, plain', 37],
  ['Crackers, saltines', 51],
  ['Crackers, wheat', 38],
  ['Crackers, whole-wheat', 71],
  ['Cucumber, peeled', 0],
  ['Cucumber, with peel', 45],
  ['Dandelion greens, boiled', 35],
  ['Duck, domesticated, roasted', 444],
  ['Egg white, raw', 16],
  ['Egg, whole, raw,', 63],
  ['Egg, yolk, raw,', 53],
  ['Egg, hard-boiled', 78],
  ['Eggplant, boiled', 35],
  ['Endive, raw', 9],
  ['Figs, dried', 95],
  ['Fish, cod, Pacific, cooked', 89],
  ['Fish, flounder/sole, cooked', 99],
  ['Fish, haddock, cooked', 95],
  ['Fish, halibut, cooked', 119],
  ['Fish, ocean perch, Atlantic, cooked', 103],
  ['Fish, pollock, cooked', 96],
  ['Fish, roughy, orange, cooked', 89],
  ['Fish, salmon, chinook, smoked', 100],
  ['Fish, salmon, sockeye, cooked', 335],
  ['Fish, sardine, Atlantic, in oil,', 177],
  ['Fish, swordfish, cooked', 132],
  ['Fish, trout, rainbow, cooked', 144],
  ['Fish, tuna, light in water', 99],
  ['Garlic, raw', 4],
  ['Grapefruit juice, pink, raw', 96],
  ['Grapes, red or green (seedless)', 35],
  ['Hearts of palm, canned', 9],
  ['Honey', 64],
  ['Horseradish, prepared', 2],
  ['Jams and preserves', 56],
  ['Kale, cooked', 36],
  ['Kiwi fruit', 46],
  ['Kohlrabi, boiled', 48],
  ['Lamb leg, whole trimmed to 1/4″ fat,roasted', 219],
  ['Leeks, boiled', 32],
  ['Lemon juice, raw', 12],
  ['Lentils, boiled', 230],
  ['Lettuce, buttrhead', 21],
  ['Lettuce, green leaf', 8],
  ['Lettuce, iceberg', 8],
  ['Lettuce, romaine', 10],
  ['Lima beans, boiled', 216],
  ['Lime juice', 10],
  ['Lobster, northern, cooked', 83],
  ['Mango', 135],
  ['Melons, cantaloupe', 54],
  ['Melons, honeydew', 61],
  ['Milk shakes, thick chocolate', 357],
  ['Miso', 137],
  ['Mollusks, clam, raw', 63],
  ['Mollusks, oyster, raw', 57],
  ['Muffins, oat bran', 154],
  ['Muffins, wheat bran/w raisins, toasted', 106],
  ['Mung beans, sprouted, boiled', 26],
  ['Mung beans, sprouted, raw', 31],
  ['Mushrooms, boiled', 44],
  ['Mushrooms, shiitake, cooked', 81],
  ['Mushrooms, shiitake, dried', 11],
  ['Mushrooms, white, raw', 15],
  ['Mustard greens, boiled', 21],
  ['Mustard, prepared, yellow', 3],
  ['Nectarines, raw', 60],
  ['Nuts, almonds', 163],
  ['Nuts, brazil nuts', 186],
  ['Nuts, cashew, dry roasted', 163],
  ['Nuts, chestnuts, roasted', 350],
  ['Nuts, coconut meat, raw', 159],
  ['Nuts, hazelnuts or filberts', 178],
  ['Nuts, macadamia nuts, dry roasted', 203],
  ['Nuts, pecans', 196],
  ['Nuts, pine nuts, dried', 58],
  ['Nuts, pistachio nuts, dry roasted', 161],
  ['Nuts, walnuts', 185],
  ['Oat bran, cooked', 88],
  ['Oat bran, raw', 231],
  ['Oil, olive', 119],
  ['Oil, peanut', 119],
  ['Oil, sesame', 120],
  ['Oil, soybean', 120],
  ['Oil, vegetable safflower', 120],
  ['Oil, vegetable, canola', 124],
  ['Oil, vegetable, sunflower', 120],
  ['Okra, boiled', 35],
  ['Onions, boiled', 41],
  ['Onions, raw', 64],
  ['Orange juice, raw', 112],
  ['Oranges', 62],
  ['Papayas', 119],
  ['Parsley, raw', 4],
  ['Peaches', 38],
  ['Peaches, dried', 93],
  ['Peanut butter, smooth style', 94],
  ['Peanuts, dry-roasted', 166],
  ['Pears, asian', 116],
  ['Pears, raw', 96],
  ['Peas, boiled', 67],
  ['Peppers, hot chili, green', 18],
  ['Peppers, sweet, green, boiled', 38],
  ['Peppers, sweet, green, raw', 2],
  ['Pickles, dill', 8],
  ['Pineapple', 78],
  ['Plantains, cooked', 179],
  ['Plantains, raw', 218],
  ['Plums, dried (prunes)', 101],
  ['Plums, raw', 30],
  ['Pork, cured, Canadian-style bacon, grilled', 86],
  ['Pork, loin, center rib (roasts)roasted', 217],
  ['Potato pancakes', 204],
  ['Potato, baked', 188],
  ['Poultry, ground turkey, cooked', 193],
  ['Pumpkin, boiled', 49],
  ['Radishes, raw', 1],
  ['Raspberries, raw', 64],
  ['Rice, brown, long-grain, cooked', 216],
  ['Rice, white, long-grain, cooked', 205],
  ['Rutabagas, boiled', 66],
  ['Sauce, salsa', 4],
  ['Sauce, teriyaki,', 16],
  ['Sauerkraut, canned', 45],
  ['Seaweed, kelp, raw', 4],
  ['Seaweed, spirulina, dried', 3],
  ['Seeds, pumpkin/squash kernels, roasted', 148],
  ['Seeds, sesame seed kernels', 50],
  ['Seeds, sunflower seed kernel', 186],
  ['Snacks, popcorn, air-popped', 31],
  ['Soup, beef broth', 29],
  ['Soy sauce', 8],
  ['Soybeans, green, boiled', 254],
  ['Soybeans, mature , boiled', 298],
  ['Soymilk', 132],
  ['Spaghetti, whole wheat', 174],
  ['Spices, celery seed', 8],
  ['Spices, chili powder', 8],
  ['Spices, cinnamon, ground', 6],
  ['Spices, curry powder', 7],
  ['Spices, garlic powder', 9],
  ['Spices, onion powder', 7],
  ['Spices, oregano, dried', 5],
  ['Spices, paprika', 6],
  ['Spices, parsley, dried', 4],
  ['Spices, pepper, black', 5],
  ['Spinach, boiled', 41],
  ['Spinach, raw', 7],
  ['Squash, summer, boiled', 36],
  ['Squash, summer, raw', 18],
  ['Squash, winter, baked', 76],
  ['Strawberries, raw', 53],
  ['Sweet potato, baked, with skin', 131],
  ['Sweet potato, boiled, without skin', 119],
  ['Syrup, maple', 52],
  ['Tahini', 89],
  ['Tangerines', 45],
  ['Tapioca, pearl, dry', 544],
  ['Tofu, firm', 57],
  ['Tofu, soft', 73],
  ['Tomatillos, raw', 11],
  ['Tomato juice, can', 41],
  ['Tomato products paste', 215],
  ['Tomato products puree', 95],
  ['Tomatoes, average', 22],
  ['Tomatoes, sun-dried', 5],
  ['Trail mix with chocolate chips, nuts and seeds', 707],
  ['Turkey, dark meat roasted', 157],
  ['Turkey, light meat roasted', 132],
  ['Turnip greens, boiled', 29],
  ['Turnips, boiled', 34],
  ['Vanilla extract', 12],
  ['Vinegar, cider', 3],
  ['Watermelon, raw', 46],
  ['Wheat flour, whole grain', 407],
  ['Wild rice, cooked', 166],
  ['Yogurt, plain, skim milk', 127],
  ['Yogurt, plain, whole milk', 138]
]

food_list.each do |name, calories|
  Food.create( name: name, calories: calories )
end
